Add active page styling and hover styling to navigation links
ccoutts2/effortless-interior-design pull request #10
Opened 2024-06-24 15:49 UTC by ccoutts2

Simple active page and hover state styling for nav links. 

We can adjust when he refactor styling

2024-07-25 11:09 UTC, kabirseth4 requested changes
Two smol changes

2024-07-25 11:09 UTC, kabirseth4 commented on src/components/navigation/NavLink/NavLink.tsx
>    label?: string;
Need to make this non-optional

2024-07-25 11:09 UTC, kabirseth4 commented on src/components/navigation/NavLink/NavLink.tsx
> +        className={`hover:border-b-2 hover:border-[#5d3a40] ${pathname === href ? "border-b-2 border-[#5d3a40]" : ""}`}
If I go to /schemes/bedroom, schemes is not underlined. Should it be if pathname.startsWith(href)?

2024-07-25 11:09 UTC, kabirseth4 requested changes
Two smol changes

2024-07-27 13:11 UTC, ccoutts2 commented
@kabirseth4 

Changes

- Remove optional prop tag from label
- Refactor pathname so dynamic pages from schemes page attach the pathname styling to the schemes nav link

2024-08-12 18:07 UTC, kabirseth4 approved these changes
All looks good to me. Will merge

2024-08-13 19:16 UTC, merged