19/cookies modal/feat
ccoutts2/effortless-interior-design pull request #11
Opened 2024-06-25 10:31 UTC by ccoutts2

- Basic cookie functionality accept or reject request
- Basic styling for time being

2024-07-25 11:35 UTC, kabirseth4 requested changes

2024-07-25 11:35 UTC, kabirseth4 commented on src/components/buttons/Button/Button.tsx
Not necessarily essential, but I think we should start extending our props from the HTML elements where possible:

```typescript
interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  label: string;
}

export const Button = ({ label, ...defaultProps }: ButtonProps) => {
  return (
    <button
      className="mx-0 my-[0.75rem] h-auto w-auto bg-[#744442] px-[1.8rem] py-2 text-xs uppercase tracking-[1px] text-[#f3eee8]"
      {...defaultProps}
    >
      {label}
    </button>
  );
};
```

2024-07-25 11:35 UTC, kabirseth4 commented on src/components/Cookie/Cookie.tsx
> +  const [consent, setConsent] = useState(false);
Will probs need to chuck this in a context at some point, but fine here for now I think

2024-07-25 11:36 UTC, kabirseth4 requested changes
Small change with button props

2024-08-13 19:06 UTC, ccoutts2 commented on src/components/buttons/Button/Button.tsx
I agree. I've just started doing this elsewhere coincidentally

2024-08-13 19:09 UTC, merged